# Generated by Django 5.1.2 on 2024-10-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0003_alter_sources_created_at_alter_sources_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='description',
        ),
        migrations.AddField(
            model_name='sources',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoria'),
        ),
    ]
