# Generated by Django 5.1.2 on 2024-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0005_rename_category_sources_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='description',
            field=models.JSONField(blank=True, default=list, verbose_name='Descripción -> lista de ideas principales'),
        ),
    ]
