# Generated by Django 5.1.2 on 2024-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0006_alter_sources_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='description',
            field=models.CharField(blank=True, verbose_name='Descripción -> lista de ideas principales'),
        ),
    ]
