# Generated by Django 5.1.2 on 2024-10-26 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sources',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
