# Generated by Django 5.1.2 on 2024-10-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0002_sources_created_at_sources_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='link',
            field=models.URLField(unique=True, verbose_name='link de la fuente'),
        ),
    ]
