# Generated by Django 5.1.2 on 2024-10-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0004_remove_sources_description_sources_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sources',
            old_name='category',
            new_name='description',
        ),
    ]
