# Generated by Django 5.1.2 on 2024-10-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0008_categories_remove_sources_description_cat_x_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Categoria. Si pertenece a mas de una, separalas por una coma'),
        ),
    ]
