# Generated by Django 5.1.2 on 2024-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterSources', '0009_alter_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='resumen',
            field=models.TextField(default='Sin resumen'),
            preserve_default=False,
        ),
    ]
